apiVersion: v1
kind: PersistentVolume
metadata:
  name: sewayuk-mariadb-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sewayuk-mariadb-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: sewayuk-mariadb-secret
stringData:
  MYSQL_DATABASE: sewayuk
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: P@ssw0rd
  MYSQL_USER: dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sewayuk-mariadb
  labels:
    app: sewayuk-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sewayuk-mariadb
  template:
    metadata:
      name: sewayuk-mariadb
      labels:
        app: sewayuk-mariadb
    spec:
      containers:
        - name: sewayuk-mariadb
          image: telkomindonesia/debian:mariadb-10.2
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: sewayuk-mariadb-secret

---

apiVersion: v1
kind: Service
metadata:
  name: sewayuk-mariadb-service
spec:
  selector:
    app: sewayuk-mariadb
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
